### ISSUE TITLE
Getting error with cli: "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by jonkemp** [BibleJS/BibleApp#17]
``` bash
$ bible --lang en '2 Peter 3:9-18'
Reference: 2 Peter 3:9-18
/usr/local/lib/node_modules/bible/node_modules/bible.js/lib/index.js:97
                    for (var i = 0; i < verses.length; ++i) {
                                              ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/bible/node_modules/bible.js/lib/index.js:97:47
    at Request._callback (/Users/.../.bible/en/index.js:32:20)
    at self.callback (/Users/.../.bible/en/node_modules/request/request.js:123:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.self.clientErrorHandler (/Users/.../.bible/en/node_modules/request/request.js:244:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:82:20)
```

``` bash
$ node -v
v4.2.1
```

**Comment by IonicaBizau** [comment]
Hmm, did you get any errors when you run first time the `bible` command? Also, do an `ls ~/.bible/en`.

It's working here using node 5.0.0, but you just discovered a little thing: https://github.com/BibleJS/bible.js/issues/9

The error is not correctly handled there. :fire: 
Thanks for heads-up!

**Comment by jonkemp** [comment]
I think I know what happened. The bible.org domain is blocked at work. :cry: I tried it at home and it worked fine. I updated to the latest version and it still worked. Sorry! Close it if you need to.

**Comment by IonicaBizau** [comment]
@jonkemp Oh, I see! I will close it when the error is handled correctly. It shouldn't crash but show a friendly error that something went wrong.

**Comment by IonicaBizau** [comment]
Fixed in https://github.com/BibleJS/bible.js/pull/13

**Comment by DanielValahul** [comment]
It appears that this error is still present in the BibleApp. The only commands I ran were
` $ npm i -g bible`

and 

`bible --lang ro`

and 
`bible Ioan 3:16`

Here is the complete error

```
 /usr/local/lib/node_modules/bible/node_modules/bible.js/lib/index.js:97
                    for (var i = 0; i < verses.length; ++i) {
                                               ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/bible/node_modules/bible.js/lib/index.js:97:48
    at /home/[user]/.bible/en/lib/index.js:22:24
    at maybeCallback (/home/[user]/.bible/en/node_modules/jsonrequest/lib/index.js:57:24)
    at Function.<anonymous> (/home/[user]/.bible/en/node_modules/tinyreq/lib/index.js:58:9)
    at res (/home/[user]/.bible/en/node_modules/assured/lib/index.js:27:12)
    at IncomingMessage.<anonymous> (/home/[user]/.bible/en/node_modules/tinyreq/lib/index.js:101:13) 
```
